### ISSUE TITLE
Why does Expurgation have 3 difficulties?

### ISSUE THREAD

**Issue by ElastedAlorian** [CNE-Ports/cnep-tricky#1]
Doesn't it normally have one difficulty, that being impossible mode or something like that?

**Comment by KittySleeper** [comment]
yea thats weird

**Comment by WizardMantis441** [comment]
not sure what you mean, there's only an unfair difficulty?
![image](https://user-images.githubusercontent.com/77557487/219042411-528418f9-0ce0-4b86-8a21-64da89820c70.png)

**Comment by WizardMantis441** [comment]
don't mind the light mode i'm on a school computer rn lmao
